name: Release

on:
  push:
    branches:
      - main

jobs:
  clinical:
    name: Release OpenAPI Specification
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@catalysthealth'
      - name: Bump Version
        uses: 'phips28/gh-action-bump-version@master'
        with:
          tag-prefix: 'v'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Export Tag
        id: tag_name
        run: |
          echo ::set-output name=TAG::`cat package.json | jq -r .version`
        shell: bash
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.tag_name.outputs.TAG }}
          files: |
            openapi/spec3.yml
            openapi/spec3.json

      - name: Publish Package
        run: |
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
