name: Release

on: tag

jobs:
  deploy:
    - name: Release
      with:
        name: ${{ steps.tag_name.outputs.TAG }}
        files: |
          openapi/spec3.yml
          openapi/spec3.json

    - name: Publish Package
      run: |
        npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
