name: Release

on:
  push:
    tags: v*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Release
      uses: softprops/action-gh-release@v0.1.13
      with:
        fail_on_unmatched_files: true
        files: |
          openapi/spec3.yml
          openapi/spec3.json
