name: Release

on:
  push:
    tags: v*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Release
      uses: softprops/action-gh-release@v0.1.13
      with:
        files: |
          openapi/spec3.yml
          openapi/spec3.json

    - name: Publish Package
      run: |
        npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
